language: python
python:
- 3.6
- 3.7
- 3.8
cache: pip
before_install:
#- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
- npm install npm@latest -g
install:
- pip3 install tox-travis
before_script:
- pip3 install -r requirements.txt
script:
- pip3 install -U python-dotenv
- tox
before_deploy:
- pip3 install bumpversion pypandoc
- sudo apt-get update
- sudo apt-get install pandoc
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github
deploy:
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: 3.8
    branch: lib
- provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASSWORD"
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  on:
    python: 3.8
    tags: true